### ISSUE TITLE
How to convert bindings or quads to standard representations?

### ISSUE THREAD

**Issue by markmelville** [belayeng/quadstore-comunica#3]
I've been able to use these quadstore libraries to quickly create a server for a linked data experiment. It's really fantastic work.

All the examples I've seen simply console.log the Quads or Bindings from the ResultsStream. I was hoping to find a way to convert these to the standard RDF formats: Turtle, RDF/XML, and JSON-LD. Do such utils not exist in this library? Is there some other library that would be recommended for that task?

**Comment by jacoscaz** [comment]
Hello @markmelville! Thank you for the kind words!

The Comunica framework https://comunica.dev/ has serialization components (and federation components, given your other comment) and there’s more libraries available at https://rdf.js.org .

The reason why quadstore-comunica, which is distribution of a very specific specific configuration of the Comunica framework, does not ship with serialization components is that the goal for quadstore and quadstore-comunica is to be a small(-ish), embeddable database (think SQLite) rather than an end-to-end solution.

In your case, I would suggest either to use a library from https://rdf.js.org. or to fork quadstore-comunica and add whatever components you need by editing its configuration files. Actually, an even easier way to quickly test things out would be to simply use the full version of Comunica (https://comunica.dev/docs/query/getting_started/query_app/) with quadstore as the data source. I would first do that, evaluate the results and, if I were happy with them, progress to extending quadstore-comunica with the additional components you actually need.

**Comment by jacoscaz** [comment]
@markmelville were you able to make any progress on this? May I close this issue?

**Comment by markmelville** [comment]
Thanks for the tips. I have made progress, but haven't yet reached the point I had hoped. That's not related to this project, though.
